server:
  port: 9090
spring:
  application:
    name: category-service
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:category-db
    username: admin
    password: 1111
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true

logging:
  level:
    root: #root seviyesinde loglama(yani uygulmadaki tüm modüller için geçerli)
    com.hnd: DEBUG