spring:
  application:
    name: product-service
  profiles:
    active: localhost
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:product-db
    username: admin
    password: 1111
    driverClassName: org.h2.Driver
  h2:
    console:
      enabled: true
  main:
    allow-bean-definition-overriding: true
info:
  component: Product Service

server:
  port: 9788

logging:
  level:
    root: #root seviyesinde loglama(yani uygulmadaki tüm modüller için geçerli)
    com.hnd: DEBUG
---
spring:
  config:
    activate:
      on-profile: localhost
  cloud:
    config:
      uri: http://localhost:8888

#  jpa:
#    hibernate:
#      ddl-auto: update
#    database-platform: org.hibernate.dialect.PostgreSQLDialect
#    properties:
#      hibernate:
#        default_schema: stock_management
#  datasource:
#    url: "jdbc:postgresql://localhost:5432/stock_management"
#    username: postgres
#    password: admin



